name: 🚀 Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🏗️ Build & Sync
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: 🛠️ Install & Build
        run: |
          npm install
          npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via SFTP
        run: |
          lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" sftp://${{ secrets.FTP_SERVER }} <<EOF
          mirror -R ./_site/ ./
          bye
          EOF
